name: Go

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    name: Build and Test
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3

    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.21'
        cache: true
        
    - name: Install dependencies
      run: cd go && go mod download

    - name: Run golangci-lint
      uses: golangci/golangci-lint-action@v3
      with:
        version: latest
        working-directory: go
        args: --timeout=5m

    - name: Run tests
      run: cd go && go test -v ./... -coverprofile=coverage.txt -covermode=atomic

    - name: Upload coverage to Codecov
      uses: codecov/codecov-action@v3
      with:
        file: ./go/coverage.txt
        flags: unittests

    - name: Build
      run: cd go && go build -v ./cmd/movery

  release:
    name: Create Release
    needs: build
    runs-on: ubuntu-latest
    if: startsWith(github.ref, 'refs/tags/')
    
    steps:
    - uses: actions/checkout@v3

    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.21'

    - name: Build for multiple platforms
      run: |
        cd go
        GOOS=linux GOARCH=amd64 go build -o movery-linux-amd64 ./cmd/movery
        GOOS=windows GOARCH=amd64 go build -o movery-windows-amd64.exe ./cmd/movery
        GOOS=darwin GOARCH=amd64 go build -o movery-darwin-amd64 ./cmd/movery

    - name: Create Release
      uses: softprops/action-gh-release@v1
      with:
        files: |
          go/movery-linux-amd64
          go/movery-windows-amd64.exe
          go/movery-darwin-amd64
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} 